### ISSUE TITLE
table communes

### ISSUE THREAD

**Issue by olivierdurr** [3liz/qgis-openads-plugin#7]
Bonjour,
je suis Olivier DÜRR de l'agence d'urbanisme lorraine-nord (AGAPE) et je suis en train de tester le plugin car nous allons utiliser openads avec lizmap; et quelque chose semble ne pas fonctionner, mais il est possible que ce soit un bug du plugin cadastre;
en effet la table communes du plugin openads semble aller chercher ses données dans la table commune_majic du plugin cadastre; or, cette table ne se remplit pas correctement; il semble que les traits d'union ne soit pas bien admis (certains passent et d'autres non), et il y a alors moins d'entité dans communes_majic que dans geo_commune; je pense que vous devriez utiliser geo_commune ou la table commune pour peupler la table communes du plugin openads; en effet ces tables sont toujours bien remplies.
J'ai essayé sur 3 communautés de communes différentes et pour la première dans la table communes j'avais 33 communes sur les 42 de geo_commune; pour la deuxième 36 sur 41; et pour la troisième 15 sur 27; toutes les communes rejetées avaient un ou deux traits d'union dans le nom et ne se trouvaient pas dans commune_majic du plugin cadastre; pourtant dans cette table il y a certaines communes avec des traits d'union !!!
Voilà, j'espère avoir bien suivi les instructions; je dois dire que je n'ai pas trop bien compris le contributing guidelines

**Comment by Gustry** [comment]
Merci pour ce ticket.

En effet, ce n'est pas une demande propre à l'extension openads, mais plus sur l'extension Cadastre qui s'occupe de l'import des données majic.

OpenADS ne fait que consommer les données de l'import.

Lien avec le ticket su Cadastre : https://github.com/3liz/QgisCadastrePlugin/issues/333

**Comment by olivierdurr** [comment]
En effet, mais dans votre plugin, j'ai juste changé la table d'import en
mettant la table commune plutôt que la table commune_majic et tout est
rentré dans l'ordre;
en tous cas je l'ai signalé sur le plugin cadastre.
Merci

*Olivier DÜRR*
*Chargé d'études*

*Système d'Information Géographique*


*AGAPE |* agence d'urbanisme et de développement durable Lorraine Nord
Visitez notre site Internet : www.agape-lorrainenord.eu
Suivez-nous sur Facebook
<https://www.facebook.com/Agence-durbanisme-AGAPE-157031411406117> et
LinkedIn <https://www.linkedin.com/company/agence-d-urbanisme-agape>
Ligne directe : (+33) 03 55 26 00 14 | Tél : (+33) 03 55 26 00 10
Espace Jean Monnet | Bâtiment Eurobase 2| F-54810 LONGLAVILLE



[image: www.datagences.eu] <http://www.datagences.eu>

**Comment by Gustry** [comment]
Le problème est du côté de l'extension, je clos ce ticket. Cela sera dans la prochaine version de l'extension Cadastre.
